import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // A leading underscore marks a parameter the contract requires but this
      // implementation deliberately does not read, such as the arguments of the
      // unconfigured auth adapter. Declared once here instead of worked around
      // at every call site.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
    },
  },
  globalIgnores([
    '.next*/**',
    'out/**',
    'next-env.d.ts',
    // `node_modules*/` rather than `node_modules/`: a dependency tree that has
    // been moved aside and not yet deleted -- a half-finished `npm ci`, a
    // side-by-side install for comparison -- matches neither the default ignore
    // nor a literal `node_modules/`, and linting the copy reports tens of
    // thousands of problems that belong to nothing in this repository.
    'node_modules*/**',
    '.qa-*/**',
    'qa-*.png',
    '.lint-report.json',
    // Untracked QA / visual scratch scripts (.tmp-*.mjs).
    // These are playwright snapshot and visual-QA helpers — not application
    // source, not imported by anything in src/ or tests/. Excluded here so a
    // truncated or partially-written working file cannot fail the lint gate.
    '.tmp-*.mjs',
    // Accidental nested checkout of this repository. Not source.
    'knoux-store/**',
    // Standalone visual prototype in the repository root, generated by a
    // third-party tool (see its own README). It is TRACKED, not untracked —
    // an earlier comment here claimed otherwise, which made this exclusion
    // look like it was hiding application code.
    //
    // It is not application code: nothing under src/ or tests/ imports it, no
    // build input references it, and its particle system was superseded by
    // src/lib/knouxField.ts. It is excluded only so its own standalone
    // JavaScript style cannot fail the KNOuX application lint gate.
    'remix-regal-portrait-with-imme/**',
  ]),
]);
