'use client';
import { useEffect, useState } from 'react';
import { WORDPRESS_ACTIONS, confirmationFor, isWordPressMutation, type WordPressAction, type WordPressOperation } from '@/lib/wordpress/operations';
import type { WordPressExecutorResult } from '@/lib/wordpress/executor';

export function OperationsConsole() {
  const [config, setConfig] = useState<{ state: string; siteIds: string[]; message: string } | null>(null);
  const [siteId, setSiteId] = useState('');
  const [action, setAction] = useState<WordPressAction>('site.probe');
  const [slug, setSlug] = useState('');
  const [reference, setReference] = useState('');
  const [review, setReview] = useState<WordPressOperation | null>(null);
  const [approved, setApproved] = useState(false);
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<WordPressExecutorResult | null>(null);
  useEffect(() => { let active = true; void fetch('/api/wordpress/operations', { cache: 'no-store' }).then(async (response) => { const value = await response.json(); if (active) setConfig(response.ok ? value : { state: 'AUTH_REQUIRED', siteIds: [], message: 'Sign in as an allowlisted operator to inspect site operations.' }); }).catch(() => { if (active) setConfig({ state: 'EXECUTOR_NOT_CONNECTED', siteIds: [], message: 'Operation configuration could not be read.' }); }); return () => { active = false; }; }, []);
  function propose() { setResult(null); setApproved(false); setReview({ siteId, action, requestId: crypto.randomUUID(), ...(/^(plugin|theme)\./.test(action) ? { slug } : {}), ...(['restore', 'migration', 'deploy'].includes(action) ? { reference } : {}) }); }
  async function execute() {
    if (!review || busy || (isWordPressMutation(review.action) && !approved)) return;
    setBusy(true);
    try { const response = await fetch('/api/wordpress/operations', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...review, ...(isWordPressMutation(review.action) ? { confirmation: confirmationFor(review) } : {}) }) }); const value = await response.json(); setResult(value.state ? value : { state: 'AUTH_REQUIRED', requestId: review.requestId, externalReference: null, version: null, items: [], measuredAt: new Date().toISOString(), message: 'The server refused the operation.' }); }
    catch { setResult({ state: 'EXECUTOR_NOT_CONNECTED', requestId: review.requestId, externalReference: null, version: null, items: [], measuredAt: new Date().toISOString(), message: 'Transport failed. Reconcile this request ID with the trusted executor before repeating a mutation.' }); }
    finally { setBusy(false); }
  }
  return <section className="wp-operations-console" aria-label="Trusted WordPress operations"><header><span className="label label--signal">TRUSTED OPERATIONS / {config?.state ?? 'UNTESTED'}</span><h3>Operate the actual install.</h3><p>{config?.message ?? 'Reading executor configuration…'}</p></header><div className="wp-operation-fields"><label>Configured site<select value={siteId} onChange={(event) => { setSiteId(event.target.value); setReview(null); }}><option value="">Select a site</option>{config?.siteIds.map((id) => <option key={id}>{id}</option>)}</select></label><label>Structured action<select value={action} onChange={(event) => { setAction(event.target.value as WordPressAction); setReview(null); }}>{WORDPRESS_ACTIONS.map((item) => <option key={item}>{item}</option>)}</select></label>{/^(plugin|theme)\./.test(action) ? <label>WordPress.org slug<input value={slug} maxLength={80} onChange={(event) => { setSlug(event.target.value); setReview(null); }} placeholder="plugin-or-theme-slug" /></label> : null}{['restore', 'migration', 'deploy'].includes(action) ? <label>Trusted executor reference<input value={reference} maxLength={120} onChange={(event) => { setReference(event.target.value); setReview(null); }} placeholder="Existing backup, migration or deployment ID" /></label> : null}</div><button type="button" className="action" disabled={!siteId || busy || !config?.siteIds.length} onClick={propose}>Review operation ↗</button>{review ? <aside className="wp-operation-review"><h4>{isWordPressMutation(review.action) ? 'Confirm a site mutation' : 'Review read-only probe'}</h4><p>{review.action} · {review.siteId} · {review.slug ?? review.reference ?? 'No extra arguments'}</p><p>Request {review.requestId}. Execution occurs only on the configured trusted adapter. Browser input never becomes a shell command. A mutation may change or interrupt the site; the executor must enforce access, backups and idempotency.</p>{isWordPressMutation(review.action) ? <label className="wp-operation-approval"><input type="checkbox" checked={approved} onChange={(event) => setApproved(event.target.checked)} />I approve this exact operation on this site.</label> : null}<button type="button" className="action" disabled={busy || (isWordPressMutation(review.action) && !approved) || result?.state === 'RUNNING' || result?.state === 'SUCCEEDED'} onClick={() => void execute()}>{busy ? 'RUNNING' : 'Send structured request ↗'}</button></aside> : null}{result ? <div className="wp-operation-receipt" role="status"><strong>{result.state}</strong><p>{result.message}</p><dl><dt>Receipt</dt><dd>{result.externalReference ?? 'None received'}</dd><dt>Version</dt><dd>{result.version ?? 'UNKNOWN'}</dd><dt>Measured</dt><dd>{result.measuredAt ?? 'No executor measurement'}</dd></dl>{result.items?.map((item) => <p key={item.slug}>{item.slug} · {item.version ?? 'UNKNOWN'} · {item.active === null ? 'ACTIVATION UNKNOWN' : item.active ? 'ACTIVE' : 'INACTIVE'}</p>)}</div> : null}</section>;
}
